name: Pipeline Action

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node
            
              uses: actions/setup-node@v3
              with:
                    node-version: 20
            - name: Install dependencies
              run: npm install --prefix project-backend

            - name: Install ts-node
              run: npm i -D typescript ts-node --prefix project-backend
            - name: Install types
              run: npm i -D ts-jest @types/jest --prefix project-backend
            - name: Run ESLint
              run: npm run lint --prefix project-backend
              
            - name: Run test
              run: npm test --prefix project-backend
            - name: Run coverage
              run: npm run ts-node-coverage --prefix project-backend
            - name: Check coverage threshold
              run: |
                COVERAGE_THRESHOLD=$(jq -r '.total.lines.pct' project-backend/coverage/coverage-final.json | awk '{print ($1 >= 75) ? "pass" : "fail"}')
                if [ "$COVERAGE_THRESHOLD" == "fail" ]; then
                  echo "Coverage is below 85%"
                  exit 1
                else
                  echo "Coverage is 85% or above"
                fi